name: ht_auth_repository
description: A repository package that provides an abstraction layer over authentication operations.
repository: https://github.com/headlines-toolkit/ht-auth-repository
publish_to: none

environment:
  sdk: ^3.8.0

dependencies: 
  ht_auth_client:
    git:
      url: https://github.com/headlines-toolkit/ht-auth-client.git
  ht_kv_storage_service:
    git:
      url: https://github.com/headlines-toolkit/ht-kv-storage-service.git
  ht_shared:
    git:
      url: https://github.com/headlines-toolkit/ht-shared.git
  
dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^9.0.0
